name: steel_soul
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+8

environment:
 sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_crashlytics: ^5.0.5
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.10
  go_router: ^14.0.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4

  injectable: ^2.5.1
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.3.0
  equatable: ^2.0.7
  image_picker: ^1.2.1
  intl: ^0.20.2
  animated_custom_dropdown: ^3.1.1
  logger: ^2.6.2
  google_fonts: ^6.2.1
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4




dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  freezed: ^2.4.6
  injectable_generator: ^2.4.1

  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
  
  uses-material-design: true

# THIS MUST BE AT THE TOP LEVEL (Zero Indentation)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21